### ISSUE TITLE
Build fails on Raspberry Pi 3 running Ubuntu

### ISSUE THREAD

**Issue by nonnymoose** [hypersad/atom-armv7l#1]
I tried to use these instructions to compile Atom on my Raspberry Pi 3 model B running Ubuntu Server.
Near the end of the build process, it failed (~ 3hrs in):
![image](https://user-images.githubusercontent.com/19860432/34546173-cb579aa6-f0b7-11e7-806b-b03d5b09a94f.png)

After this, `startup.js` is **not** present in `atom/out/`.

`uname -a`:
```
Linux <hostname removed> 4.4.0-1080-raspi2 #88-Ubuntu SMP Mon Dec 11 14:23:15 UTC 2017 armv7l armv7l armv7l GNU/Linux
```
`lsb_release -a`:
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```
Free RAM before and after building: **804M** (I had killed my DE and X server to allocate more RAM)

**Comment by hypersad** [comment]
Keep in mind that if build failed at packaging step you could use `--existing-binaries` argument with `script/build` to save time, steps like transpiling paths will be skipped. Before rebuilding I also recommend to remove `apm/package-lock.json` to prevent reinstalling `apm`.

1. Use `--max_old_space_size`:
This argument needs to be given to `node`, but because `script/build` calls it via `env`, let's call it directly: firstly, locate your `node`. If you installed it via `nvm`, the path would be like `/home/pi/.nvm/versions/node/v9.3.0/bin/node`. Then change shebang in `script/build` to it and pass this argument. First line would look like that:
```
#!/home/pi/.nvm/versions/node/v9.3.0/bin/node --max_old_space_size=2048`
```

2. Increase open files limit:
```
ulimit -n 4096
```

**Comment by nonnymoose** [comment]
Okay! I have done that and will let you know how it goes.

**Comment by hypersad** [comment]
Closed due to inactivity.
